[package]
name = "restore-pixel-art-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
clap = { version = "4", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
